###
DELETE {{url_base}}/v1/drivers/10020

###
PUT {{url_base}}/v1/drivers
Content-Type: application/json

{
  "id" : 10023,
  "name": "Usuario 2K",
  "age": 20
}

###
POST {{url_base}}/v1/drivers
Content-Type: application/json

{
  "name": "Usuario 3K",
  "age": 15
}

###
GET {{url_base}}/v1/drivers
Accept: application/json

