###
DELETE {{url_base}}/v1/drivers/10005

###
PUT {{url_base}}/v1/drivers
Content-Type: application/json

{
  "id" : 10020,
  "name": "Usuario 10020",
  "age": 20
}

###
POST {{url_base}}/v1/drivers
Content-Type: application/json

{
  "name": "Usuario 2",
  "age": 15
}

###
GET {{url_base}}/v1/drivers
Accept: application/json

