###
DELETE {{url_base}}/v1/drivers/10020

###
PUT {{url_base}}/v1/drivers
Content-Type: application/json

{
  "id" : 10024,
  "name": "Usuario 4K",
  "age": 25
}

###
POST {{url_base}}/v1/drivers
Content-Type: application/json

{
  "name": "Usuario 4K",
  "age": 15
}

###
GET {{url_base}}/v1/drivers
Accept: application/json

