CREATE TABLE driver (
    id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    age INTEGER NOT NULL,
    CONSTRAINT driver_pk PRIMARY KEY (id)
);

CREATE SEQUENCE SEQ_DRIVER START WITH 10000 INCREMENT BY 1;